name: verificac19
description: Unofficial EU Digital Green Certificate validation SDK for Flutter apps
version: 1.3.0
homepage: https://github.com/mastro993/verificac19-flutter
documentation: https://github.com/mastro993/verificac19-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  archive: ^3.1.6
  asn1lib: ^1.0.3
  cbor: ^4.1.0
  clock: ^1.1.0
  crypto: ^3.0.1
  crypto_keys: ^0.3.0
  dart_base45: ^1.0.1
  dio: ^4.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.3
  ninja: ^3.0.7
  retrofit: ^3.0.1
  x509b: ^0.2.5

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  hive_generator: ^1.1.1
  http_mock_adapter: ^0.3.2
  injectable_generator: ^1.5.2
  mockito: ^5.0.17
  retrofit_generator: ^3.0.1+1
